version: "3"
services:
    backend:
        container_name: backend
        image: ghcr.io/dcontt00/arq_backend:latest
        ports: 
            - "3001:3001"
    frontend:
        container_name: frontend
        image: ghcr.io/dcontt00/arq_frontend:latest
        ports: 
            - "80:80"
